### ISSUE TITLE
[Core Feature] Add a database to store Tasks

### ISSUE THREAD

**Issue by hXtreme** [hXtreme/tasks3#8]
### Description

Create a database to store and query tasks.
The database should for each task store:
```yaml
--- 
id: taskid
title: Title
urgency: 2            # Int from 0 to 4
importance: 2         # Int from 0 to 4
tags: 
  - tag1
  - tag2
folder: None
description: >-
    This is a very detailed
    description of the task.
```

### What can be used

SQLAlchemy can be used to interface with the database and we can either use SQLite or Postgress SQL as the backend database.
